name: Build
on: [push, pull_request]

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.x'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install go dependencies
      run: |
        go mod download
    - name: Build go-diydns
      run: make build-all